version: '3.9'

services:
  api1:
    restart: on-failure
    build: ./api
    environment:
      - PUBLIC_URL=https://interecom.de
      - API_URL=https://interecom.de/api
      - NODE_ENV=production
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/:ro

  web:
    restart: on-failure
    build: ./web
    environment:
      - PUBLIC_URL=https://interecom.de
      - API_URL=https://interecom.de/api
      - NODE_ENV=production
    ports:
      - '3000:3000'

  nginx:
    build: ./nginx
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - api1
      - web
