version: '3.9'

services:

  api1:
    restart: on-failure
    build: ./api
    environment:
      - PUBLIC_URL=http://159.89.108.59 
      - API_URL=http://159.89.108.59/api
      - NODE_ENV=production
    ports:
      - '4000:4000'
    env_file:
      - .env

  web:
    restart: on-failure
    build: ./web
    environment:
      - PUBLIC_URL=http://159.89.108.59 
      - API_URL=http://159.89.108.59/api
      - NODE_ENV=production
    ports:
      - '3000:3000'

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api1
      - web