version: '3.9'
services:
  web1:
    restart: on-failure
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1